memes = [
    'https://www.care.com/c/wp-content/uploads/sites/2/2021/03/memes-for-kids-1.png',
    'https://i.pinimg.com/474x/ee/05/48/ee054872761d9054bacf8c2c1e97ee73.jpg',
    'https://preview.redd.it/nxrbxj9eljd21.jpg?width=640&crop=smart&auto=webp&s=44ba3e63076b16b12ac092504074e1dfd9c2d38a',
    'https://forums-cdn.spongepowered.org/uploads/default/original/3X/d/0/d0399730b419ac7f72a00aa5bbea30946ce9b0d5.jpeg',
    'https://www.care.com/c/wp-content/uploads/sites/2/2021/03/memes-for-kids-4.png',
    'https://i.ytimg.com/vi/P0ADL0_-Cag/maxresdefault.jpg',
    'https://i.pinimg.com/564x/0d/fd/a3/0dfda353d53c879c73fb5c5d55e89c03.jpg',
    'https://www.care.com/c/wp-content/uploads/sites/2/2021/03/memes-for-kids-6.png',
    'https://preview.redd.it/g4vm7de3q4j51.jpg?width=640&crop=smart&auto=webp&s=6b1a2d277669b91f713fc7484e57e20de98b97c3',
    'https://preview.redd.it/8ze5zhn5m1g61.gif?width=676&format=mp4&s=bb264df062c4bbe50741b47486fb659f3116cc47',
    'https://cdn-useast1.kapwing.com/static/templates/always-has-been-meme-template-full-be5848f2.webp',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgz7OQSV_y5pLNrA3cqYPmikoYwfYqbsPRmQ&s',
    'https://cdn-useast1.kapwing.com/static/templates/shut-up-and-take-my-money-meme-template-full-dac9d95b.webp',
    'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BB1raLyw.img?w=690&h=388&m=6',
    'https://preview.redd.it/the-kendrick-mustard-of-duty-meme-is-huge-right-now-v0-evovdf5yrnve1.jpeg?auto=webp&s=0428c2e728bf7d41cd67829ed996b8e7918a99e8',
    'https://pbs.twimg.com/media/EXDk0oYWkAEBe7D.jpg',
    'https://static.wikia.nocookie.net/jerma-lore/images/a/a4/Whentheimposterissus.png/revision/latest/scale-to-width-down/250?cb=20210123063951',
    'https://media.tenor.com/xKifZxFX42oAAAAM/meme-doge.gif',
    'https://pbs.twimg.com/media/FLGRTliUUAMce6a.jpg',
    'https://media1.tenor.com/m/2ndcvKu-928AAAAd/bring-out-the-fine-china.gif',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8qUan4GWRBJyJtlKPr5lDEwLBZw37tQ2rKQ&s',
]

meme_descriptions = [
    'The look you give your friend when your teacher says to find a partner',
    'Me: *puts on hand sanitizer* A cut I never knew existed:',
    'When you flush the toilet and the water starts rising',
    'I love sleep because its like a time machine to breakfast',
    'When the bell rings and the teacher forgot to mention homework',
    'POV: You entered the wrong classroom',
    'Shout out to old people for graduating high school without google',
    'When the waiter asks how the food is...',
    'Teacher hypes up class party all year The Party:',
    'You can copy my homework, but dont make it obvious',
    'Always has been',
    '5 stars',
    'People trying to get sold out supplies at the grocery store',
    'Eye of Rah',
    'Call of Mustard',
    'Only a spoonful',
    'When the imposter is sus',
    'Doge',
    'Roblox man face',
    'Honey we have guests Bring out the Fine China',
    '40+ year old pluggnb rapper 🔥🙏 did unc snap?',
]

function searchContent(){
    
}